In [2]:
import numpy as np


NumPy: dasar-dasar mutlak untuk pemula

`1. PENGENALAN NumPy`

NumPy (Numerical Python) adalah pustaka Python sumber terbuka yang digunakan di hampir semua bidang ilmu pengetahuan dan teknik. NumPy adalah standar universal untuk bekerja dengan data numerik dalam Python, dan merupakan inti dari ekosistem Python ilmiah dan PyData. Pengguna NumPy mencakup semua orang, mulai dari pembuat kode pemula hingga peneliti berpengalaman yang melakukan penelitian dan pengembangan ilmiah dan industri mutakhir. API NumPy digunakan secara luas di Pandas, SciPy, Matplotlib, scikit-learn, scikit-image, dan sebagian besar paket Python sains dan ilmiah lainnya.

NumPy menyediakan ndarray, sebuah objek larik n-dimensi yang homogen, dengan metode-metode untuk mengoperasikannya secara efisien. NumPy dapat digunakan untuk melakukan berbagai macam operasi matematika pada larik. NumPy menambahkan struktur data yang kuat ke dalam Python yang menjamin perhitungan yang efisien dengan larik dan matriks, serta menyediakan pustaka fungsi matematika tingkat tinggi yang sangat banyak yang beroperasi pada larik dan matriks.

`2. CARA MENGINSTAL NumPy`

Jika Anda sudah memiliki Python, Anda dapat menginstal NumPy dengan :

In [3]:
pip instal numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: unknown command "instal" - maybe you meant "install"



`3. CARA MENGIMPOR NumPy`

In [4]:
import numpy as np

`4. MEMBACA CONTOH KODE`

Jika Anda melihat >>>, Anda sedang melihat input, atau kode yang akan Anda masukkan. Segala sesuatu yang tidak memiliki >>> di depannya adalah output, atau hasil dari menjalankan kode Anda. Ini adalah gaya yang Anda lihat ketika Anda menjalankan python di baris perintah, tetapi jika Anda menggunakan IPython,

In [5]:
>>> a = np.arange(6) 
>>> a2 = a[np.newaxis, :]
>>> print(a2.shape)

(1, 6)


`5. APA PERBEDAAN ANTARA DAFTAR Python DAN LARIK NumPy ?`

NumPy memberikan Anda banyak sekali cara cepat dan efisien untuk membuat larik dan memanipulasi data numerik di dalamnya. Meskipun sebuah daftar Python dapat berisi tipe
data yang berbeda dalam satu daftar, semua elemen dalam larik NumPy harus homogen. Operasi matematika yang seharusnya dilakukan pada larik akan sangat tidak efisien jika larik tidak homogen.

Mengapa menggunakan NumPy ?

Larik NumPy lebih cepat dan lebih ringkas daripada daftar Python. Larik menggunakan lebih sedikit memori dan nyaman digunakan. NumPy menggunakan lebih sedikit memori untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data. Hal ini memungkinkan kode dioptimalkan lebih jauh lagi.

`6. APA YANG DIMAKSUD DENGAN ARRAY ?`

Larik adalah struktur data utama dari pustaka NumPy. Larik adalah sebuah larik nilai dan berisi informasi mengenai data mentah, bagaimana menemukan sebuah elemen, dan bagaimana menginterpretasikan sebuah elemen. Array memiliki kisi-kisi elemen yang dapat diindeks dengan berbagai cara. Elemen-elemen tersebut memiliki tipe yang sama, yang disebut sebagai dtype array.

Larik dapat diindeks oleh tuple bilangan bulat nonnegatif, oleh boolean, oleh larik lain, atau oleh bilangan bulat. Pangkat larik adalah jumlah dimensi. Bentuk larik adalah sebuah tupel bilangan bulat yang memberikan ukuran larik di setiap dimensi. 

In [6]:
>>> a = np.array([1, 2, 3, 4, 5, 6])

#atau

>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
>>> print(a[0])

[1 2 3 4]


`7. INFORMASI LEBIH LANJUT TENTANG ARRAY`

Bagian ini mencakup larik 1D, larik 2D, ndarray, vektor, matriks.

Anda mungkin sesekali mendengar larik yang disebut sebagai "ndarray", yang merupakan singkatan dari "larik N-dimensi". Larik N-dimensi adalah larik dengan sejumlah dimensi. Anda
mungkin juga pernah mendengar larik 1-D, atau larik satu dimensi, 2-D, atau larik dua dimensi, dan seterusnya. Kelas NumPy ndarray digunakan untuk merepresentasikan matriks dan
vektor. Sebuah vektor adalah sebuah larik dengan satu dimensi (tidak ada perbedaan antara vektor baris dan kolom), sedangkan
matriks mengacu pada larik dengan dua dimensi. Untuk larik 3-D atau larik berdimensi lebih tinggi, istilah tensor juga biasa digunakan.

`Apa saja atribut dari sebuah larik ?`

Larik biasanya merupakan wadah dengan ukuran tetap untuk item dengan jenis dan ukuran yang sama. Jumlah dimensi dan item dalam larik ditentukan oleh bentuknya. Bentuk larik adalah sebuah tupel bilangan bulat non-negatif yang menentukan ukuran setiap dimensi. Di NumPy, dimensi disebut sumbu. Ini berarti bahwa jika Anda memiliki larik 2D yang terlihat
seperti ini :

In [7]:
A = np.array([[0., 0., 0.],
              [1., 1., 1.]])
print(A)

[[0. 0. 0.]
 [1. 1. 1.]]


Larik Anda memiliki 2 sumbu. Sumbu pertama memiliki panjang 2 dan sumbu kedua memiliki panjang 3.

Atribut larik mencerminkan informasi yang melekat pada larik itu sendiri. Jika Anda perlu mendapatkan, atau bahkan mengatur, properti larik tanpa membuat larik baru, Anda dapat mengakses larik melalui atributnya.

`8. CARA MEMBUAT LARIK DASAR`

Bagian ini mencakup np.array(), np.zeros(), np.ones(), np empty(), np.arange(), np.linspace(), dtype. Untuk membuat larik NumPy, Anda dapat menggunakan fungsi np.array().

In [8]:
>>> import numpy as np

>>> a = np.array([1, 2, 3])
>>> print(a)

[1 2 3]


Selain membuat larik dari urutan elemen, Anda dapat dengan mudah membuat larik yang berisi angka 0:

In [9]:
>>> zeros_array = np.zeros(2)
>>> print(zeros_array)

[0. 0.]


larik yang diisi dengan angka 1 :

In [10]:
>>> ones_array = np.ones(2)
>>> print(ones_array)

[1. 1.]


Atau bahkan l a r i k kosong! Fungsi empty membuat larik yang isi awalnya acak dan bergantung pada kondisi memori. Alasan untuk menggunakan kosong daripada nol (atau sesuatu yang serupa) adalah kecepatan - pastikan untuk mengisi setiap elemen setelahnya !

In [11]:
>>> empty_array = np.empty(2)
>>> print(empty_array)

[1. 1.]


Anda dapat membuat larik dengan sejumlah elemen :

In [12]:
>>> array = np.arange(4)
>>> print(array)

[0 1 2 3]


Dan bahkan larik yang berisi kisaran interval dengan jarak yang sama. Untuk melakukan ini, Anda akan menentukan angka pertama, angka terakhir, dan ukuran langkah.

In [13]:
arr = np.arange(2, 9, 2)
print(arr)

[2 4 6 8]


Anda juga dapat menggunakan np.linspace() untuk membuat larik dengan nilai yang diberi spasi linear dalam interval tertentu:

In [14]:
arr = np.linspace(0, 10, num=5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


Menentukan tipe data 

Meskipun tipe data default adalah floating point (np.float64), Anda dapat secara eksplisit menentukan tipe data yang Anda inginkan dengan menggunakan kata kunci dtype.


In [15]:
x = np.ones(2, dtype = np.int64)
print(x)

[1 1]


`9. MENAMBAHKAN, MENGHAPUS, DAN MENYORTIR ELEMEN`

Bagian ini mencakup np.sort(), np.concatenate().

Mengurutkan elemen sangat mudah dengan np.sort(). Anda dapat menentukan sumbu, jenis, dan urutan ketika Anda memanggil fungsi tersebut. Jika Anda memulai dengan array ini :

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


Selain mengurutkan, yang mengembalikan salinan larik yang diurutkan, Anda dapat menggunakan :
- argsort, yang merupakan pengurutan tidak langsung di sepanjang sumbu tertentu,
- lexsort, yang merupakan pengurutan stabil tidak langsung pada beberapa tombol,
- pencarian terurut, yang akan menemukan elemen dalam larik terurut, dan
- partisi, yang merupakan pengurutan parsial.

Untuk membaca lebih lanjut tentang pengurutan array, lihat: sort.
Jika Anda memulai dengan array ini :

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Anda dapat menggabungkannya dengan np.concatenate().
print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


Atau, jika Anda memulai dengan susunan ini :

In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

# Anda dapat menggabungkannya dengan :
print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


`10. BAGAIMANA ANDA MENGETAHUI BENTUK DAN UKURAN ARRAY ?`

Bagian ini mencakup ndarray.ndim, ndarray.size, ndarray.shape.
ndarray.ndim akan memberi tahu Anda jumlah sumbu, atau dimensi, dari larik. ndarray.size akan memberi tahu Anda jumlah total elemen larik. Ini adalah hasil kali dari elemen-elemen bentuk larik.

ndarray.shape akan menampilkan sebuah tupel bilangan bulat yang menunjukkan jumlah elemen yang disimpan di setiap dimensi larik. Misalnya, jika Anda memiliki larik 2-D dengan 2 baris dan 3 kolom, bentuk larik Anda adalah (2, 3).

Contohnya, jika Anda membuat larik ini :

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# Untuk menemukan jumlah dimensi array, jalankan :
print(array_example.ndim)

3


In [20]:

# Untuk menemukan jumlah total elemen dalam larik, jalankan :
print(array_example.size)

24


In [21]:

# Dan untuk menemukan bentuk array Anda, jalankan :
print(array_example.shape)

(3, 2, 4)


`11. DAPATKAH ANDA MEMBENTUK ULANG SEBUAH LARIK ?`

Bagian ini mencakup arr.reshape(). 

Menggunakan arr.reshape() akan memberikan bentuk baru pada larik tanpa mengubah datanya. Ingatlah bahwa ketika Anda menggunakan metode reshape, larik yang ingin Anda buat harus memiliki jumlah elemen yang sama dengan larik aslinya. Jika Anda memulai dengan larik dengan 12 elemen, Anda harus memastikan bahwa larik baru Anda juga memiliki total 12 elemen.

Jika Anda memulai dengan array ini :

In [22]:
>>> a = np.arange(6)
>>> print(a)

[0 1 2 3 4 5]


Anda dapat menggunakan reshape() untuk membentuk ulang larik Anda. Sebagai contoh, Anda dapat membentuk ulang larik ini menjadi larik dengan tiga baris dan dua kolom :

In [23]:
>>> b = a.reshape(3, 2)
>>> print(b)

[[0 1]
 [2 3]
 [4 5]]


Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional :

In [24]:
>>> np.reshape(a, newshape = (1, 6), order = 'C')

array([[0, 1, 2, 3, 4, 5]])

`a` adalah larik yang akan dibentuk ulang.

`newshape` adalah bentuk baru yang Anda inginkan. Anda dapat menentukan sebuah bilangan bulat atau sebuah tupel bilangan bulat. Jika Anda menentukan bilangan bulat, hasilnya adalah larik dengan panjang tersebut. Bentuknya harus sesuai dengan bentuk aslinya.

`order: C` berarti membaca/menulis elemen menggunakan urutan indeks seperti C, F berarti membaca/menulis elemen menggunakan urutan indeks seperti Fortran, A berarti membaca/menulis elemen dalam urutan indeks seperti Fortran jika a bersebelahan dengan Fortran dalam memori, urutan seperti C sebaliknya. (Ini adalah parameter opsional dan tidak perlu ditentukan).

Pada dasarnya, urutan C dan Fortran berkaitan dengan bagaimana indeks sesuai dengan urutan larik yang disimpan dalam memori. Pada Fortran, ketika bergerak melalui elemen-elemen larik dua dimensi ketika disimpan di memori, indeks `pertama` adalah indeks yang paling cepat berubah. Ketika indeks pertama berpindah ke baris berikutnya saat berubah, matriks disimpan satu kolom pada satu waktu. Inilah sebabnya mengapa Fortran dianggap sebagai `bahasa` yang
`mengutamakan kolom`. Di C di sisi lain, indeks `terakhir` berubah paling cepat. Matriks disimpan berdasarkan baris, menjadikannya sebagai `bahasa utama-Baris`. Apa yang Anda
lakukan untuk C atau Fortran tergantung pada apakah lebih penting untuk mempertahankan konvensi pengindeksan atau tidak mengurutkan ulang data.

`12. CARA MENGONVERSI LARIK 1D MENJADI LARIK 2D (CARA MENAMBAHKAN SUMBU BARU KE LARIK)`

Bagian ini mencakup np.newaxis, np.expand_dims.

Anda dapat menggunakan np.newaxis dan np.expand_dims untuk menambah dimensi larik yang ada.

Menggunakan np.newaxis akan meningkatkan dimensi larik Anda sebanyak satu dimensi ketika digunakan sekali. Ini berarti larik 1D akan menjadi larik 2D, larik 2D akan menjadi larik
3D, dan seterusnya.

Contohnya, jika Anda memulai dengan array ini :

In [25]:
>>> a = np.array([1, 2, 3, 4, 5, 6])
>>> a. shape

(6,)

Anda dapat menggunakan np.newaxis untuk menambahkan sumbu baru :

In [26]:
>>> a2 = a[np.newaxis, :]
>>> a2.shape

(1, 6)

Anda dapat secara eksplisit mengonversi larik 1D dengan vektor baris atau vektor kolom menggunakan np.newaxis. Sebagai contoh, Anda dapat mengonversi larik 1D menjadi vektor
baris dengan menyisipkan sumbu di sepanjang dimensi pertama :

In [27]:
>>> row_vector = a[np.newaxis, :]
>>> row_vector.shape

(1, 6)

Atau, untuk vektor kolom, Anda dapat menyisipkan sumbu di sepanjang dimensi kedua :

In [28]:
>>> col_vector = a[:, np.newaxis]
>>> col_vector.shape

(6, 1)

Anda juga dapat memperluas larik dengan menyisipkan sumbu baru pada posisi tertentu dengan np.expand_dims.

Contohnya, jika Anda memulai dengan array ini :

In [29]:
>>> a = np.array([1, 2, 3, 4, 5, 6])
>>> a. shape

(6,)

Anda dapat menggunakan np.expand_dims untuk menambahkan sumbu pada posisi indeks 1 dengan :

In [30]:
>>> b = np.expand_dims(a, axis=1)
>>> b. shape

(6, 1)

Anda dapat menambahkan sumbu pada posisi indeks 0 dengan :

In [31]:
>>> c = np.expand_dims(a, axis=0)
>>> c. shape

(1, 6)

`13. MENGINDEKS DAN MENGIRIS`

Anda dapat mengindeks dan mengiris larik NumPy dengan cara yang sama seperti mengiris daftar Python.

In [32]:
data = np.array([1, 2, 3])
print(data [1])

2


In [33]:
print(data [0:2])

[1 2]


In [34]:
print(data[1:])

[2 3]


In [35]:
print(data[-2:])

[2 3]


Anda mungkin ingin mengambil sebagian larik atau elemen larik tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. Untuk melakukan itu, Anda perlu melakukan
subset, irisan, dan/atau indeks larik Anda.

Jika Anda ingin memilih nilai dari larik Anda yang memenuhi kondisi tertentu, sangat mudah dengan NumPy.

Contohnya, jika Anda memulai dengan array ini :

In [36]:
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Anda dapat dengan mudah mencetak semua nilai dalam larik yang kurang dari 5.
>>> print(a[a < 5])

[1 2 3 4]


Anda juga dapat memilih, misalnya, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks larik.

In [37]:
>>> five_up = (a >= 5)
>>> print(a[five_up])

[ 5  6  7  8  9 10 11 12]


Anda dapat memilih elemen yang dapat dibagi 2 :

In [38]:
>>> dibagi_oleh_2 = a[a%2==0]
>>> print(dibagi_oleh_2)

[ 2  4  6  8 10 12]


Atau Anda dapat memilih elemen yang memenuhi dua kondisi dengan menggunakan operator & dan | :

In [39]:
>>> c = a[(a > 2) & (a < 11)]
>>> print(c)

[ 3  4  5  6  7  8  9 10]


Anda juga dapat menggunakan operator logika & dan | untuk mengembalikan nilai boolean yang menentukan apakah nilai dalam larik memenuhi kondisi tertentu atau tidak. Hal ini dapat berguna pada larik yang berisi nama atau nilai kategorikal lainnya.

In [40]:
>>> five_up = (a > 5) | (a == 5)
>>> print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


Anda juga dapat menggunakan np.nonzero() untuk memilih elemen atau indeks dari larik. Dimulai dengan larik ini :

In [41]:
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Anda dapat menggunakan np.nonzero() untuk mencetak indeks elemen y a n g , misalnya, kurang dari 5.
>>> b = np.nonzero(a < 5)
>>> print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


Dalam contoh ini, sebuah tuple array dikembalikan: satu untuk setiap dimensi. Larik pertama mewakili indeks baris di mana nilai-nilai ini ditemukan, dan larik kedua mewakili indeks kolom di mana nilai-nilai tersebut ditemukan.

Jika Anda ingin membuat daftar koordinat di mana elemen-elemennya ada, Anda dapat meng-zip array, mengulang daftar koordinat, dan mencetaknya. Sebagai contoh :

In [42]:
>>> list_of_coordinates= list(zip(b[0], b[1]))
>>> for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


Anda juga dapat menggunakan np.nonzero() untuk mencetak elemen dalam larik yang kurang dari 5 dengan :

In [43]:
>>> print(a[b])

[1 2 3 4]


Jika elemen yang Anda cari tidak ada dalam larik, maka larik indeks yang dikembalikan akan kosong. Sebagai contoh :

In [44]:
>>> not_there = np.nonzero(a == 42)
>>> print(not_there)

(array([], dtype=int64), array([], dtype=int64))


`14. CARA MEMBUAT LARIK DARI DATA YANG SUDAH ADA`

Bagian ini mencakup pengirisan dan pengindeksan, np.vstack(), np.hstack(), np.hsplit(), .view(), copy().

Anda dapat dengan mudah membuat larik baru dari bagian larik yang sudah ada. Katakanlah Anda memiliki larik ini :

In [45]:
>>> a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Anda dapat membuat larik baru dari bagian larik Anda kapan saja dengan menentukan di mana Anda ingin memotong larik Anda.
>>> arr1 = a[3:8]
>>> arr1

array([4, 5, 6, 7, 8])

Di sini, Anda mengambil bagian dari larik Anda dari posisi indeks 3 hingga posisi indeks 8.

Anda juga dapat menumpuk dua larik yang ada, baik secara vertikal maupun horizontal. Katakanlah Anda memiliki dua larik, a1 dan a2 :

In [46]:
>>> a1 = np.array([[1, 1],
                   [2, 2]])
>>> a2 = np.array([[3, 3],
                   [4, 4]])

# Anda dapat menumpuknya secara vertikal dengan vstack :
>>> np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Atau susun secara horizontal dengan hstack :

In [47]:
>>> np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Anda dapat membagi sebuah larik menjadi beberapa larik yang lebih kecil dengan menggunakan hsplit. Anda dapat menentukan jumlah larik yang berbentuk sama untuk dikembalikan atau kolom-kolom yang akan dibagi.

Katakanlah Anda memiliki susunan ini :

In [48]:
>>> x = np.arange(1, 25).reshape(2, 12)
>>> x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Jika Anda ingin membagi larik ini menjadi tiga larik dengan bentuk yang sama, Anda akan menjalankannya :

In [49]:
>>> np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Jika Anda ingin membagi larik Anda setelah kolom ketiga dan keempat, Anda akan menjalankannya :

In [50]:
>>> np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

Anda dapat menggunakan metode view untuk membuat objek larik baru yang melihat data yang sama dengan larik asli (salinan dangkal).

Tampilan adalah konsep NumPy yang penting! Fungsi-fungsi NumPy, dan juga operasi-operasi seperti pengindeksan dan pemotongan, akan mengembalikan tampilan bila memungkinkan. Hal ini akan menghemat memori dan lebih cepat (tidak perlu menyalin data). Namun, penting untuk menyadari hal ini - memodifikasi data pada suatu tampila juga akan mengubah larik aslinya !

Katakanlah Anda membuat larik ini :

In [51]:
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Sekarang kita membuat larik b1 dengan mengiris a dan memodifikasi elemen pertama dari b1. Ini akan memodifikasi elemen yang sesuai di a juga !

In [52]:
>>> b1 = a[0, :]
>>> b1

array([1, 2, 3, 4])

In [53]:
>>> b1[0] = 99
>>> b1

array([99,  2,  3,  4])

In [54]:
>>> a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Menggunakan metode salin akan membuat salinan lengkap larik dan datanya (salinan dalam). Untuk menggunakan ini pada larik Anda, Anda dapat menjalankan :

In [55]:
>>> b2 = a.copy()
>>> print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


`15. OPERASI LARIK DASAR`

Bagian ini mencakup penjumlahan, pengurangan, perkalian, pembagian, dan lainnya Setelah Anda membuat array, Anda dapat mulai bekerja dengannya. Katakanlah, misalnya, Anda telah membuat dua larik, satu bernama "data" dan satu lagi bernama "ones". Anda dapat menambahkan array bersama-sama dengan tanda plus.

In [56]:
>>> data = np.array([1, 2])
>>> ones = np.ones(2, dtype = int)
>>> data + ones

array([2, 3])

Tentu saja, Anda bisa melakukan lebih dari sekadar penambahan!

In [57]:
>>> data - ones

array([0, 1])

In [58]:
>>> data * data

array([1, 4])

In [59]:
>>> data / data

array([1., 1.])

Operasi dasar sangat sederhana dengan NumPy. Jika Anda ingin mencari jumlah dari elemen-elemen di dalam sebuah larik, Anda dapat menggunakan sum(). Ini bekerja untuk larik 1D, larik 2D, dan larik dengan dimensi yang lebih tinggi.

In [60]:
>>> a = np.array([1, 2, 3, 4])
>>> a.sum()

10

Untuk menambahkan baris atau kolom dalam larik 2D, Anda akan
menentukan sumbu. Jika Anda memulai dengan array ini :

In [61]:
>>> b = np.array([[1, 1], [2, 2]])

# Anda dapat menjumlahkan di atas sumbu baris dengan :
>>> b.sum(axis=0)

array([3, 3])

Anda dapat menjumlahkan di atas sumbu kolom dengan :

In [62]:
>>> b.sum(axis=1)

array([2, 4])

`16. PENYIARAN`

Ada kalanya Anda mungkin ingin melakukan operasi antara larik dan angka tunggal (juga disebut operasi antara vektor dan skalar) atau antara larik dengan dua ukuran berbeda. Sebagai contoh, larik Anda (kita sebut saja "data") mungkin berisi informasi mengenai jarak dalam mil, namun Anda ingin mengubah informasi tersebut menjadi kilometer. Anda dapat melakukan operasi ini dengan :

In [63]:
>>> data = np.array([1.0, 2.0])
>>> data * 1.6

array([1.6, 3.2])

NumPy memahami bahwa perkalian harus terjadi pada setiap sel. Konsep ini disebut broadcasting. Broadcasting adalah sebuah mekanisme yang memungkinkan NumPy untuk melakukan operasi pada larik dengan bentuk yang berbeda. Dimensi dari larik Anda haruslah kompatibel, contohnya, ketika dimensi dari kedua lariknya sama atau ketika salah satunya adalah 1. Jika dimensinya tidak kompatibel, maka Anda akan mendapatkan ValueError.

`17. OPERASI LARIK YANG LEBIH BERGUNA`

Bagian ini mencakup nilai maksimum, minimum, jumlah, rata-rata, produk, deviasi standar, dan lainnya.

NumPy juga melakukan fungsi agregasi. Selain min, max, dan sum, Anda dapat dengan mudah menjalankan mean untuk mendapatkan rata-rata, prod untuk mendapatkan hasil perkalian elemen-elemennya , std untuk mendapatkan deviasi standar, dan banyak lagi.

In [64]:
>>> data.max()

2.0

In [65]:
>>> data.min()

1.0

In [66]:
>>> data.sum()

3.0

Mari kita mulai dengan larik ini, yang disebut "a".

In [67]:
>>> a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
                  [0.54627315, 0.05093587, 0.40067661, 0.55645993],
                  [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

Sangat umum jika Anda ingin menjumlahkan sepanjang baris atau kolom. Secara default, setiap fungsi agregasi NumPy akan mengembalikan penjumlahan seluruh larik. Untuk menemukan jumlah atau minimum dari elemen-elemen dalam larik Anda, jalankan :

In [68]:
>>> a.sum()

4.8595784

In [69]:
>>> a.min()

0.05093587

Anda dapat menentukan pada sumbu mana Anda ingin fungsi agregasi dihitung. Sebagai contoh, Anda dapat menemukan nilai minimum dalam setiap kolom dengan menentukan sumbu=0.

In [70]:
>>> a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

`18. MEMBUAT MATRIKS`

Anda dapat mengoper daftar Python untuk membuat larik 2-D(atau "matriks") untuk merepresentasikannya di NumPy.

In [71]:
>>> data = np.array([[1, 2], [3, 4], [5, 6]])
>>> data

array([[1, 2],
       [3, 4],
       [5, 6]])

Operasi pengindeksan dan pemotongan berguna saat Anda memanipulasi matriks :

In [72]:
>>> data[0, 1]

2

In [73]:
>>> data [1:3]

array([[3, 4],
       [5, 6]])

In [74]:
>>> data [0:2, 0]

array([1, 3])

Anda dapat menggabungkan matriks dengan cara yang sama seperti menggabungkan vektor :

In [75]:
>>> data.max()

6

In [76]:
>>> data.min()

1

In [77]:
>>> data.sum()

21

Anda dapat menggabungkan semua nilai dalam matriks dan Anda dapat menggabungkannya di seluruh kolom atau baris menggunakan parameter sumbu. Untuk mengilustrasikan hal ini,
mari kita lihat kumpulan data yang sedikit dimodifikasi : 

In [78]:
>>> data = np.array([[1, 2], [5, 3], [4, 6]])
>>> data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [79]:
>>> data.max(axis=0)

array([5, 6])

In [80]:
>>> data.max(axis=1)

array([2, 5, 6])

Anda dapat menambahkan dan mengalikannya menggunakan
operator aritmatika jika Anda memiliki dua matriks dengan ukuran yang sama.

In [81]:
>>> data = np.array([[1, 2], [3, 4]])
>>> ones = np.array([[1, 1], [1, 1]])
>>> data + ones

array([[2, 3],
       [4, 5]])

Pada kasus ini, NumPy akan menggunakan aturan broadcast untuk melakukan operasi tersebut.

In [82]:
>>> data = np.array([[1, 2], [3, 4], [5, 6]])
>>> ones_row = np.array([[1, 1]])
>>> data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

Perlu diketahui bahwa ketika NumPy mencetak array N-dimensi, sumbu terakhir akan dilingkari paling cepat sementara sumbu pertama adalah yang paling lambat. Sebagai contoh :

In [83]:
>>> np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Sering kali kita ingin NumPy menginisialisasi nilai dari sebuah larik. NumPy menawarkan fungsi-fungsi seperti ones() dan zeros(), dan kelas random.Generator untuk menghasilkan
angka acak untuk itu. Yang perlu Anda lakukan adalah memasukkan jumlah elemen yang ingin Anda hasilkan :

In [84]:
>>> np.ones(3)

array([1., 1., 1.])

In [85]:
>>> np.zeros(3)

array([0., 0., 0.])

In [86]:
>>> rng = np.random.default_rng()
>>> rng.random(3)

array([0.34282644, 0.75221532, 0.70657112])

Anda juga dapat menggunakan ones(), zeros(), dan random() untuk membuat larik 2D jika Anda memberikan tuple yang menggambarkan dimensi matriks :

In [87]:
>>> np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
>>> np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
>>> rng.random((3, 2))

array([[0.02993415, 0.44948194],
       [0.15378389, 0.06708084],
       [0.71315813, 0.44742755]])

`19. MENGHASILKAN ANGKA ACAK`

Penggunaan pembangkitan angka acak adalah bagian penting dari konfigurasi dan evaluasi banyak algoritma numerik dan pembelajaran mesin. Apakah Anda perlu menginisialisasi bobot secara acak dalam jaringan saraf tiruan, membagi data ke dalam
set acak, atau mengacak set data Anda secara acak, kemampuan untuk menghasilkan bilangan acak (sebenarnya, bilangan acak semu yang dapat diulang) sangat penting.

Dengan Generator.integer, Anda dapat menghasilkan bilangan bulat acak dari rendah (ingat bahwa ini inklusif dengan NumPy) hingga tinggi (eksklusif). Anda dapat mengatur endpoint = True untuk membuat angka tinggi menjadi inklusif.

Anda dapat membuat larik 2 x 4 bilangan bulat acak antara 0 dan 4 dengan :

In [90]:
>>> rng.integers(5, size=(2, 4))

array([[2, 1, 3, 2],
       [1, 2, 3, 3]], dtype=int64)

`20. CARA MENDAPATKAN ITEM DAN JUMLAH UNIK`

Bagian ini mencakup np.unique().

Anda dapat menemukan elemen unik dalam larik dengan mudah
menggunakan np.unique. Sebagai contoh, jika Anda memulai
dengan larik ini :

In [91]:
>>> a = np.array([11, 11, 12, 13, 14, 14, 15, 16, 17, 12, 13, 11, 14, 18,
19, 20])

# Anda dapat menggunakan np.unique untuk mencetak nilai unik dalam larik Anda:
>>> nilai_unik = np.unique(a)
>>> print(nilai_unik)

[11 12 13 14 15 16 17 18 19 20]


Untuk mendapatkan indeks nilai unik dalam larik NumPy (larik posisi indeks pertama dari nilai unik dalam larik ), cukup berikan argumen return_index dalam np.unique() serta larik
Anda.

In [92]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  6  7  8 13 14 15]


Anda dapat memberikan argumen return_counts di np.unique() bersama dengan larik Anda untuk mendapatkan hitungan frekuensi nilai unik dalam larik NumPy.

In [93]:
>>> unique_values, occurrence_count = np.unique(a, return_counts=True)
>>> print(occurrence_count)

[3 2 2 3 1 1 1 1 1 1]


Hal ini juga bisa dilakukan dengan array 2D! Jika Anda memulai dengan array ini :

In [94]:
>>> a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1,
2, 3, 4]])

# Anda dapat menemukan nilai unik dengan :
>>> nilai_unik = np.unique(a_2d)
>>> print(nilai_unik)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Jika argumen sumbu tidak dilewatkan, array 2D Anda akan diratakan.

Jika Anda ingin mendapatkan baris atau kolom yang unik, pastikan untuk memberikan argumen axis. Untuk menemukan baris unik, tentukan axis = 0 dan untuk kolom, tentukan axis = 1.

In [95]:
>>> unique_rows = np.unique(a_2d, axis=0)
>>> print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Untuk mendapatkan baris unik, posisi indeks, dan jumlah kemunculan, Anda dapat menggunakan :

In [96]:
>>> unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts = True, return_index = True)
>>> print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
>>> print(indices)

[0 1 2]


In [98]:
>>> print(occurrence_count)

[2 1 1]


`21. MENGUBAH DAN MEMBENTUK ULANG MATRIKS`

Bagian ini mencakup arr.reshape(), arr.transpose(), arr.T

Adalah hal yang umum jika Anda perlu mengubah urutan matriks Anda. Larik NumPy memiliki properti T yang memungkinkan Anda untuk mentransposisi matriks.

Hal ini dapat terjadi ketika, misalnya, Anda memiliki model yang mengharapkan bentuk input tertentu yang berbeda dari
kumpulan data Anda. Di sinilah metode reshape dapat berguna. Anda hanya perlu memasukkan dimensi baru yang Anda inginkan untuk matriks.

In [99]:
>>> data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
>>> data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Anda juga dapat menggunakan .transpose() untuk membalikkan atau mengubah sumbu larik sesuai dengan nilai yang Anda tentukan.

Jika Anda memulai dengan array inI :

In [101]:
>>> arr = np.arange(6).reshape((2, 3))
>>> arr

array([[0, 1, 2],
       [3, 4, 5]])

Anda dapat melakukan transposisi larik dengan arr.transpose().

In [102]:
>>> arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

Anda juga dapat menggunakan arr.T :

In [103]:
>>> arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

`22. CARA MEMBALIKKAN LARIK`

Bagian ini mencakup np.flip().

Fungsi np.flip() dari NumPy memungkinkan Anda untuk membalik, atau membalikkan, isi larik di sepanjang sebuah sumbu. Ketika menggunakan np.flip(), tentukan larik yang ingin Anda balikkan dan sumbunya. Jika Anda tidak menentukan sumbu, NumPy akan membalikkan isi larik di sepanjang sumbu larik input Anda.

`Membalikkan larik 12`

Jika Anda memulai dengan susunan 1D seperti ini :

In [104]:
>>> arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Anda dapat membalikkan dengan :
>>> reversed_arr = np.flip(arr)

# Jika Anda ingin mencetak larik terbalik, Anda dapat menjalankannya:
>>> print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


`Membalikkan larik 2D`

Larik 2D bekerja dengan cara yang hampir sama. Jika Anda memulai dengan array ini :

In [105]:
>>> arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# membalikkan konten di semua baris dan semua kolom dengan:
>>> reversed_arr = np.flip(arr_2d)
>>> print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Anda dapat dengan mudah membalikkan hanya baris dengan :

In [106]:
>>> reversed_arr_rows = np.flip(arr_2d, axis=0)
>>> print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Atau membalikkan hanya kolom dengan :

In [107]:
>>> reversed_arr_columns = np.flip(arr_2d, axis=1)
>>> print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


Anda juga dapat membalikkan isi hanya satu kolom atau baris. Misalnya, Anda dapat membalikkan isi baris pada posisi indeks 1 (baris kedua) :

In [108]:
>>> arr_2d[1] = np.flip(arr_2d[1])
>>> print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


Anda juga dapat membalikkan kolom pada posisi indeks 1 (kolom kedua) :

In [109]:
>>> arr_2d[:,1] = np.flip(arr_2d[:,1])
>>> print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


`23. MEMBENTUK ULANG DAN MERATAKAN SUSUNAN MULTIDIMENSI`

Bagian ini mencakup .flatten(), ravel().

Ada dua cara populer untuk meratakan larik: .flatten() dan .ravel(). Perbedaan utama antara keduanya adalah larik baru yang dibuat menggunakan ravel() sebenarnya merupakan referensi ke larik induk (yaitu, "view"). Ini berarti bahwa setiap perubahan pada larik baru akan mempengaruhi larik induk juga. Karena ravel tidak membuat salinan, maka ravel sangat efisien dalam penggunaan memori.

Jika Anda memulai dengan array ini :

In [110]:
>>> x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Ketika Anda menggunakan flatten, perubahan pada larik baru Anda tidak akan mengubah larik induk.

Sebagai contoh :

In [111]:
>>> a1 = x.flatten()
>>> a1[0] = 99
>>> print(x) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [112]:
>>> print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


Namun ketika Anda menggunakan ravel, perubahan yang Anda buat pada larik baru akan mempengaruhi larik induk. Sebagai contoh:

In [113]:
>>> a2 = x.ravel()
>>> a2[0] = 98
>>> print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [114]:
>>> print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


`24. CARA MENGAKSES DOCSTRING UNTUK INFORMASI LEBIH LANJUT`

Bagian ini mencakup help(), ?, ??

Dalam hal ekosistem sains data, Python dan NumPy dibangun dengan mempertimbangkan pengguna. Salah satu contoh terbaiknya adalah akses bawaan ke dokumentasi. Setiap objek berisi referensi ke sebuah string, yang dikenal sebagai docstring. Dalam banyak kasus, docstring ini berisi ringkasan singkat dan ringkas tentang objek dan cara menggunakannya.
Python memiliki fungsi help() bawaan yang dapat membantu Anda mengakses informasi ini. Ini berarti bahwa hampir setiap saat Anda membutuhkan informasi lebih lanjut, Anda dapat menggunakan help() untuk menemukan informasi yang Anda butuhkan dengan cepat. kebutuhan.

Sebagai contoh:

>>> help (max)
max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    Dengan argumen iterable tunggal, kembalikan item terbesarnya.
    Argumen default keyword-only menentukan objek yang akan
    dikembalikan jika iterable yang disediakan kosong.
    Dengan dua argumen atau lebih, kembalikan argumen terbesar.

Karena akses ke informasi tambahan sangat berguna, IPython menggunakan karakter ? sebagai singkatan untuk mengakses dokumentasi ini bersama dengan informasi lain yang relevan. IPython adalah sebuah command shell untuk komputasi interaktif dalam berbagai bahasa.

Sebagai contoh :

In [0]: max?
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

Dengan argumen iterable tunggal, kembalikan item terbesarnya.
Argumen default keyword-only menentukan objek yang akan
dikembalikan jika iterable yang disediakan kosong. Dengan dua argumen atau lebih, kembalikan argumen terbesar. Ketik fungsi_atau_metode bawaan.

Anda bahkan dapat menggunakan notasi ini untuk metode objek dan objek itu sendiri. Katakanlah Anda membuat larik ini :

In [12]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
# Mendapatkan dokumentasi untuk np.array
help(np.array)

# Mendapatkan dokumentasi untuk np.array
print(np.array.__doc__)


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, etc.).
  

Hal ini juga berlaku untuk fungsi dan objek lain yang Anda buat. Ingatlah untuk menyertakan docstring dengan fungsi Anda menggunakan string literal (""" """ atau ''' ''' di sekitar
dokumentasi Anda).

Contohnya , jika Anda membuat fungsi ini :

In [14]:
import numpy as np

def double(a):
    '''Kembalikan a * 2'''
    return a * 2

Anda dapat memperoleh informasi mengenai fungsi tersebut :

In [2]: double?
Tanda tangan: double(a)
Docstring: Kembalikan a* 2
File:~/Desktop/<ipython-input-23-b5adf20be596>
Ketik:fungsi

Anda dapat mencapai tingkat informasi yang lebih tinggi dengan membaca kode sumber objek yang Anda minati. Dengan menggunakan tanda tanya ganda (??), Anda dapat mengakses kode sumber.

Sebagai contoh :

Signature: double(a)
Source:
def double(a):
    '''Return a * 2'''
    return a * 2
File: ~/Desktop/<ipython-input-23-b5adf20be596>
Type: function

Jika objek yang dimaksud dikompilasi dalam bahasa selain Python, menggunakan ?? akan mengembalikan informasi yang sama dengan ?. Anda akan menemukan hal ini pada banyak objek dan tipe bawaan, misalnya :

`25. BEKERJA DENGAN RUMUS MATEMATIKA`

Kemudahan dalam mengimplementasikan rumus matematika yang bekerja pada array adalah salah satu hal yang membuat NumPy banyak digunakan dalam komunitas Python
ilmiah.

Sebagai contoh, ini adalah rumus mean square error (rumus utama yang digunakan dalam model pembelajaran mesin terawasi yang menangani regresi) :

In [26]:
import numpy as nnp
import imageio  # Jika Anda menggunakan imageio

# Baca gambar sebagai array NumPy
img_array = imageio.imread('images.jpeg')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17632\1075339437.py:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_array = imageio.imread('images.jpeg')


FileNotFoundError: No such file: 'c:\Users\ASUS\Downloads\PROLAN-KHIFAYAH NASYWA AL MISRA\images.jpeg'

Menerapkan rumus ini sederhana dan mudah di Numpy :

In [27]:
error = (1/n) * np.sum(np.square(predictions - labels-))

SyntaxError: invalid syntax (743578273.py, line 1)

In [28]:
import numpy as np

# Prediksi
predictions = np.array([1, 2, 3, 4, 5])

# Label
labels = np.array([1, 2, 3, 4, 5])

# Menghitung jumlah data (n)
n = len(predictions)

# Menghitung error
error = (1/n) * np.sum(np.square(predictions - labels))

print("Error:", error)

Error: 0.0


Apa yang membuat ini bekerja dengan sangat baik adalah bahwa `prediksi` dan `label` dapat berisi satu atau seribu nilai. Mereka hanya perlu memiliki ukuran yang sama.

`26. BAGAIMANA CARA MENYIMPAN DAN MEMUAT OBJEK NumPy`

Bagian ini mencakup `np.save`, `np.saves`, `np.savetxt`, `np.load`, `np.loadtxt`.

Ada beberapa cara untuk menyimpan dan memuat objek dengan Numpy. Objek-objek larik dapat disimpan dan dimuat dari file disk dengan fungsi `loadtxt` dan `savetxt` yang menangani file teks normal, fungsi `muat` dan `simpan` yang menangani file biner NumPy dengan ekstensi file.npy, dan fungsi `savez` yang menangani file NumPy dengan ekstensi file .npz.

File .npy dan .npz menyimpan data, bentuk, dtype, dan informasi lain yang diperlukan untuk merekonstruksi ndarray dengan cara yang memungkinkan array diambil dengan benar, bahkan ketika file tersebut berada di mesin lain dengan arsitektur yang berbeda.

Jika Anda ingin menyimpan satu objek larik tunggal, simpanlah sebagai file .npy menggunakan np.save. Jika Anda ingin menyimpan lebih dari satu objek larik dalam satu berkas, simpan sebagai berkas .npz menggunakan np.savez. Anda juga dapat menyimpan beberapa larik ke dalam satu file dalam format npz terkompresi dengan savez_compressed.

Sangat mudah untuk menyimpan dan memuat dan larik dengan np.save(). Pastikan Anda menentukan larik yang ingin Anda simpan dan nama file. Sebagai contoh, jika Anda membuat larik ini :

In [29]:
>>> a = np.array([1, 2, 3, 4, 5, 6])

Anda dapat menyimpannya sebagai "nama file.npy" dengan :

In [55]:
>>> np.save('MA23-231021006-Tugas 5.ipynb', a)

Anda dapat menggunakan np.load() untuk merekonstruksi larik Anda.

In [ ]:
>>> np.load('namafile.npy', a)

In [69]:
>>> print(a)

[1 2 3 4 5 6]


Anda dapat menyimpan larik NumPy sebagai file teks biasa seperti file .csv atau .txt dengan np.savetxt. Sebagai contoh, jika Anda membuat larik ini :

In [70]:
>>> csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Anda dapat dengan mudah menyimpannya sebagai file .csv dengan nama "new_file.csv" seperti ini :

In [71]:
>>> np.savetxt('new_file.csv', csv_arr)

Anda dapat dengan cepat dan mudah memuat file teks yang tersimpan dengan menggunakan loadtxt() :

In [72]:
>>> np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

Fungsi savetxt () dan loadtxt () menerima parameter opsional tambahan seperti header, footer, dan pembatas. Meskipun file teks lebih mudah untuk dibagikan, file .npy dan . npz lebih
kecil dan lebih cepat dibaca. Jika Anda membutuhkan penanganan yang lebih canggih untuk file teks Anda (misalnya, jika Anda perlu bekerja dengan baris yang berisi nilai yang hilang), Anda akan ingin menggunakan fungsi genfromtxt.
Dengan savetxt, Anda dapat menentukan header, footer, komentar, dan banyak lagi.

`27. MENGIMPOR DAN MENGEKSPOR CSV`

Sangat mudah untuk membaca CSV yang berisi informasi yang ada. Cara terbaik dan termudah untuk melakukannya adalah dengan menggunakan Panda.

In [ ]:
import pandas as pd

# Jika semua kolom Anda memiliki tipe yang sama:
df = pd.read_csv('housing.csv')

x = pd.read_csv('housing.csv', header=0).values
print(x)

In [ ]:
>>> import pandas as pd

>>> # Anda juga dapat memilih kolom yang Anda perlukan:
>>> x = pd.read_csv('housing.csv', usecols=['Artist', 'Plays']).values
>>> print(x)

Sangat mudah untuk menggunakan Pandas untuk mengekspor larik Anda juga. Jika Anda baru mengenal NumPy, Anda mungkin ingin membuat sebuah dataframe Pandas dari nilai-nilai di dalam larik Anda dan kemudian menulis dataframe tersebut ke sebuah file CSV dengan Pandas.

Jika Anda membuat larik ini "a"

In [10]:
>>> a = np.array([[-2.58289208, 0.43014843, -1.24082018, 1.59572603],
                  [ 0.99027828, 1.17150989, 0.94125714, -0.14692469],
                  [ 0.76989341, 0.81299683, -0.95068423, 0.11769564],
                  [ 0.20484034, 0.34784527, 1.96979195,
0.51992837]])

# Anda dapat membuat kerangka data Pandas
df = pd.DataFrame(a)
print(df)

NameError: name 'np' is not defined

Anda dapat dengan mudah menyimpan bingkai data Anda :

In [ ]:
>>> df.to_csv('pd.csv')

Dan baca CSV Anda dengan :

In [ ]:
>>> data = pd.read_csv('pd.csv')

Anda juga dapat menyimpan larik Anda dengan metode NumPy savetxt.

In [ ]:
>>> np.savetxt('np.csv', a, fmt='%.2f', delimiter=',', header='1, 2, 3, 4')

SyntaxError: unterminated string literal (detected at line 1) (446325956.py, line 1)

`28. MERENCANAKAN ARRAY DENGAN MATPLOTLIB`

Jika Anda perlu membuat plot untuk nilai-nilai Anda, caranya sangat mudah dengan `Matplotlib`.

Sebagai contoh, Anda mungkin memiliki susunan seperti ini :

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

>>> a = np.array([2, 1, 5, 7, 4, 6, 8, 14, 10, 9, 18, 20, 22])

SyntaxError: invalid syntax (4279239557.py, line 4)

Jika Anda sudah menginstal Matplotlib, Anda dapat mengimpornya :

In [ ]:
>>> import matplotlib.pyplot as plt

# Jika Anda menggunakan Jupyter Notebook, Anda mungkin juga ingin menjalankan yang berikut ini Baris kode 

# untuk menampilkan kode Anda di buku catatan: %matplotlib sebaris

Yang perlu Anda lakukan untuk memplot nilai Anda adalah menjalankannya :

In [ ]:
>>> plt.plot(a)

# Jika Anda menjalankan dari baris perintah, Anda mungkin perlu melakukan ini: # >>> plt.show()

Contohnya, Anda bisa memplot larik 1D seperti ini :

In [ ]:
>>> x = np.linspace(0, 5, 20)
>>> y = np.linspace(0, 10, 20)
>>> plt.plot(x, y, 'ungu') # baris
>>> plt.plot(x, y, 'o') # titik-titik

Dengan Matplotlib, Anda memiliki akses ke banyak sekali opsi visualisasi.

In [120]:
>>> fig = plt.figure()
>>> ax = fig.add_subplot(proyeksi='3d')
>>> X = np.arange(-5, 5, 0.15)
>>> Y = np.arange(-5, 5, 0.15)
>>> X, Y = np.meshgrid(X, Y)
>>> R = np.sqrt(X**2 + Y**2)
>>> Z = np.sin(R)
>>> ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap='viridis')

NameError: name 'plt' is not defined